# -*- coding: utf-8 -*-
"""Stock Portfolio Tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P6l0fdhYzr7KTp6UEI_Cfb-H9vGSctYK

Stock Portfolio Tracker **bold text**
"""

# Hardcoded stock prices (in USD)
stock_prices = {
    "AAPL": 180,
    "TSLA": 250,
    "GOOGL": 135,
    "MSFT": 320,
    "AMZN": 130
}

# Dictionary to store user's stock holdings
portfolio = {}

# Get user input
while True:
    stock = input("Enter stock symbol (or type 'done' to finish): ").upper()
    if stock == 'DONE':
        break
    if stock not in stock_prices:
        print("Stock not found in price list. Try again.")
        continue
    try:
        quantity = int(input(f"Enter quantity for {stock}: "))
        portfolio[stock] = portfolio.get(stock, 0) + quantity
    except ValueError:
        print("Invalid quantity. Please enter a number.")

# Calculate total investment
total_investment = 0
print("\nYour Portfolio:")
for stock, qty in portfolio.items():
    price = stock_prices[stock]
    value = qty * price
    total_investment += value
    print(f"{stock}: {qty} shares × ${price} = ${value}")

print(f"\nTotal Investment Value: ${total_investment}")

# Optional: Save to CSV file
save = input("Do you want to save the result to 'portfolio.csv'? (yes/no): ").lower()
if save == 'yes':
    with open("portfolio.csv", "w") as file:
        file.write("Stock,Quantity,Price,Value\n")
        for stock, qty in portfolio.items():
            price = stock_prices[stock]
            value = qty * price
            file.write(f"{stock},{qty},{price},{value}\n")
        file.write(f"\nTotal Investment,,,{total_investment}")
    print("Portfolio saved to 'portfolio.csv'.")